import { DefaultTheme } from "styled-components/native";

export const darkTheme: DefaultTheme =  {
    colors: {
        text: "#EDEDED",
        textInactive: "#EDEDED80",
        highlightColor: "#93FC9D",
        highlightColorInactive: "#93FC9D80",
        bgMainColor: ["#141424","#0C0C25"],
        bgColor: "#141424", 
        bdColor: "#93FC9D26",
        bgContainerColorActive: "#2A2A3C",
        bgContainerColorInactive: "#2A2A3C40",
        fadeBgColor: "#0f0f1df2",
        bgModal: "#141424",
        bgBottomTab: "#141424",
        tintActiveColor: '#93FC9D',
        tintInactiveColor: '#79769A99',
        trackColorInactive: "#474663",
        trackColorActive: "#93FC9D",
        thumbColor: "#EDEDED",
        white: "#FFFFFF",
    },
    images: {
        bgButton: require("../assets/images/dark/bgButton_dark.png"),
        catLoadingGif: require("../assets/images/common/cat_loading.gif"),
        bgWelcomeAlarms: require("../assets/images/dark/bg_WelcomeAlarms_dark.png"),
        bgWelcomeNotes: require("../assets/images/dark/bg_WelcomeNotes_dark.png"),
        bgWelcomeTodos: require("../assets/images/dark/bg_WelcomeTodos_dark.png"),
        bgWelcomeInfos: require("../assets/images/dark/bg_WelcomeInfos_dark.png"),
    },
    fonts: {
        karantinaRegular: 'Karantina-Regular',
        karantinaBold: 'Karantina-Bold',
    },
};

export const lightTheme: DefaultTheme = {
    colors: {
        text: "#110F1F",
        textInactive: "#110F1F80",
        highlightColor: "#6E53B4",
        highlightColorInactive: "#6E53B480",
        bgMainColor: ["#FFFFFF","#E8E2F8"],
        bgColor: "#E8E2F8", 
        bdColor: "#6E53B426",
        bgContainerColorActive: "#FEFEFEbf",
        bgContainerColorInactive: "#FEFEFE40",
        fadeBgColor: "#000000E6",
        bgModal: "#FEFEFE",
        bgBottomTab: "#FEFEFE",
        tintActiveColor: '#6E53B4',
        tintInactiveColor: '#110F1F99',
        trackColorInactive: "#110F1F",
        trackColorActive: "#6E53B4",
        thumbColor: "#FEFEFE",
        white: "#FEFEFE",
    },
    images: {
        bgButton: require("../assets/images/light/bgButton_light.png"),
        catLoadingGif: require("../assets/images/common/cat_loading.gif"),
        bgWelcomeAlarms: require("../assets/images/dark/bg_WelcomeAlarms_dark.png"),
        bgWelcomeNotes: require("../assets/images/dark/bg_WelcomeNotes_dark.png"),
        bgWelcomeTodos: require("../assets/images/dark/bg_WelcomeTodos_dark.png"),
        bgWelcomeInfos: require("../assets/images/dark/bg_WelcomeInfos_dark.png"),
    },
    fonts: {
        karantinaRegular: 'Karantina-Regular',
        karantinaBold: 'Karantina-Bold',
    },
};